version: '3.8'

services:
  bookly_main:
    image: docker.io/wcored/booklymain:latest
    container_name: BooklyMain
    env_file:
      - "./.env"
    ports:
      - "8082:8080"
    networks:
      - bookly_network
    volumes:
      - ./credentials:/home/app/.aws/credentials
      - ./config:/home/app/.aws/config
    depends_on:
      bookly_postgres:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/health" ]
      interval: 30s
      timeout: 3s
      retries: 3
  
  bookly_postgres:
    image: postgres:latest
    container_name: BooklyDatabase
    ports:
      - "5432:5432"
    networks:
      - bookly_network
    volumes:
      - bookly_postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    


networks:
  bookly_network:
    external: true

volumes:
  bookly_postgres_volume:
    external: true